"use client";
import { useMemo,useState } from "react";
import { FAQ } from "@/types/product";
import { Accordion,AccordionContent,AccordionItem,AccordionTrigger } from "@/components/ui/accordion";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search,ArrowRight } from "lucide-react";
import Link from "next/link";
import { EmptyState,SectionHeader,Surface } from "@/components/store-ui";
export default function FAQBrowser({faqs}:{faqs:FAQ[]}){const[query,setQuery]=useState("");const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return faqs.filter(f=>!q||[f.question,f.answer,f.category||""].some(v=>v.toLowerCase().includes(q)))},[faqs,query]);const grouped=filtered.reduce<Record<string,FAQ[]>>((a,f)=>{const k=f.category||"General";(a[k]??=[]).push(f);return a},{});return <><div className="relative mb-8"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-black/35"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your question…" className="h-12 rounded-full border-black/[.08] bg-white pl-11"/></div>{!filtered.length?<EmptyState title="No answers found" description="Try a different phrase or contact our support team." action={<Button asChild className="rounded-full bg-orange-500 hover:bg-orange-600"><Link href="/contact">Contact support</Link></Button>}/>:<div className="space-y-6">{Object.entries(grouped).map(([category,rows])=><Surface key={category} className="overflow-hidden p-2 sm:p-3"><SectionHeader eyebrow={category.toUpperCase()} title={rows.length+" question"+(rows.length===1?"":"s")}/><Accordion type="single" collapsible className="px-2 sm:px-3">{rows.map(f=><AccordionItem key={f.id} value={f.id}><AccordionTrigger className="py-5 text-left font-semibold">{f.question}</AccordionTrigger><AccordionContent><div className="prose prose-sm max-w-none pb-3 text-black/55" dangerouslySetInnerHTML={{__html:f.answer}}/></AccordionContent></AccordionItem>)}</Accordion></Surface>)}</div>}<div className="mt-8 rounded-2xl bg-[#10152b] p-6 text-white sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/45">STILL NEED HELP?</p><h2 className="mt-2 text-2xl font-bold">Talk to the Ketronics team.</h2><p className="mt-2 text-sm text-white/55">We can help with product selection, orders, delivery and technical services.</p><Link href="/contact" className="mt-5 inline-flex items-center rounded-full bg-orange-500 px-5 py-2.5 text-xs font-bold hover:bg-orange-600">Contact us <ArrowRight className="ml-2 h-4 w-4"/></Link></div></>}