"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
import { isSupabaseConfigured } from "@/lib/supabaseConfig";
import Link from "next/link";
import { Mail,Phone,MapPin,Clock,ShieldCheck,Truck } from "lucide-react";
import { ContactInfo } from "@/types/product";

export function Footer(){
 const[info,setInfo]=useState<ContactInfo[]>([]);const[settings,setSettings]=useState<Record<string,string>>({});
 useEffect(()=>{if(!isSupabaseConfigured())return;void Promise.all([supabase.from("contact_info").select("*").eq("is_active",true).order("sort_order"),supabase.from("site_settings").select("key,value").in("key",["site_name","business_hours"])]).then(([a,b])=>{setInfo(a.data||[]);setSettings(Object.fromEntries((b.data||[]).map(x=>[x.key,x.value])))}).catch(()=>{})},[]);
 const phones=info.filter(x=>x.type==="phone");const emails=info.filter(x=>x.type==="email");const addresses=info.filter(x=>x.type==="address");
 return <footer className="mt-10 bg-[#10152b] text-white"><div className="mx-auto max-w-[1400px] px-5 py-10 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[1.3fr_1fr_1fr_1.2fr]"><div><Link href="/" className="text-xl font-black tracking-[-.04em]">Ketronics</Link><p className="mt-3 max-w-sm text-sm leading-6 text-white/50">Technology for work, home and business. Shop products or talk to our team about practical technology services.</p><div className="mt-6 flex gap-3 text-[10px] font-bold text-white/45"><span className="flex items-center gap-1"><ShieldCheck className="h-3.5 w-3.5"/>Secure checkout</span><span className="flex items-center gap-1"><Truck className="h-3.5 w-3.5"/>Kenya delivery</span></div></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-white/45">Shop</h3><div className="mt-4 space-y-3 text-sm text-white/60"><Link className="block hover:text-white" href="/products">All products</Link><Link className="block hover:text-white" href="/products?category=laptops">Laptops</Link><Link className="block hover:text-white" href="/products?category=printers">Printers</Link><Link className="block hover:text-white" href="/products?category=pcs">PCs & components</Link></div></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-white/45">Company</h3><div className="mt-4 space-y-3 text-sm text-white/60"><Link className="block hover:text-white" href="/about-us">About us</Link><Link className="block hover:text-white" href="/support">Support</Link><Link className="block hover:text-white" href="/faq">FAQ</Link><Link className="block hover:text-white" href="/contact">Contact</Link></div></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-white/45">Get in touch</h3><div className="mt-4 space-y-3 text-sm text-white/60">{emails.slice(0,1).map(x=><a key={x.id} href={'mailto:'+x.value} className="flex gap-2 hover:text-white"><Mail className="h-4 w-4 shrink-0"/>{x.value}</a>)}{phones.slice(0,1).map(x=><a key={x.id} href={'tel:'+x.value} className="flex gap-2 hover:text-white"><Phone className="h-4 w-4 shrink-0"/>{x.value}</a>)}{addresses.slice(0,1).map(x=><span key={x.id} className="flex gap-2"><MapPin className="h-4 w-4 shrink-0"/>{x.value}</span>)}{settings.business_hours&&<span className="flex gap-2"><Clock className="h-4 w-4 shrink-0"/>{settings.business_hours}</span>}</div></div></div><div className="mt-10 flex flex-col gap-3 border-t border-white/10 pt-5 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Ketronics LTD. All rights reserved.</span><div className="flex gap-5"><Link href="/privacy-policy" className="hover:text-white">Privacy</Link><Link href="/terms-and-conditions" className="hover:text-white">Terms</Link></div></div></div></footer>;
}