"use client";
import { useEffect,useState } from "react";
import { useUserStore } from "@/lib/stores/userStore";
import { supabase } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { User, Mail, Phone, Save, ShoppingBag, WalletCards, Activity } from "lucide-react";
import { PageHero, StatCard, StorePage, Surface } from "@/components/store-ui";
import Link from "next/link";

export default function ProfilePage(){
 const {user,fetchUser}=useUserStore(); const[loading,setLoading]=useState(true); const[saving,setSaving]=useState(false);
 const[form,setForm]=useState({full_name:"",phone:"",email:""}); const[stats,setStats]=useState({orders:0,active:0,spent:0});
 useEffect(()=>{if(!user)return void Promise.all([supabase.from("profiles").select("full_name,phone,email").eq("id",user.id).single(),supabase.from("orders").select("status,total").eq("user_id",user.id)]).then(([p,o])=>{if(p.error)throw p.error;setForm({full_name:p.data?.full_name||"",phone:p.data?.phone||"",email:p.data?.email||user.email||""});if(!o.error){const rows=o.data||[];setStats({orders:rows.length,active:rows.filter(x=>!["delivered","cancelled","refunded","returned"].includes(x.status)).length,spent:rows.filter(x=>["paid","processing","shipped","delivered"].includes(x.status)).reduce((s,x)=>s+Number(x.total||0),0)})}}).catch(()=>toast.error("Could not load profile")).finally(()=>setLoading(false))},[user]);
 if(!user)return <StorePage><Surface className="mx-auto max-w-lg p-8 text-center"><h1 className="text-2xl font-bold">Sign in to manage your profile</h1><Button asChild className="mt-5 rounded-full bg-orange-500 hover:bg-orange-600"><Link href="/auth/login">Sign in</Link></Button></Surface></StorePage>;
 if(loading)return <StorePage><PageHero eyebrow="ACCOUNT" title="Your profile" description="Loading your account…"/><div className="h-48 animate-pulse rounded-2xl bg-white"/></StorePage>;
 const initials=(form.full_name||user.email).split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const{error}=await supabase.from("profiles").update({full_name:form.full_name.trim(),phone:form.phone.trim(),updated_at:new Date().toISOString()}).eq("id",user.id);if(error)throw error;await fetchUser();toast.success("Profile saved")}catch{toast.error("Could not save your profile")}finally{setSaving(false)}};
 return <StorePage><PageHero eyebrow="ACCOUNT" title="Your profile" description="Keep your contact details current so orders and support reach you."/><div className="grid gap-5 lg:grid-cols-[300px_1fr]"><Surface className="p-6"><div className="flex flex-col items-center text-center"><div className="flex h-24 w-24 items-center justify-center rounded-full bg-[#10152b] text-2xl font-bold text-white">{initials}</div><h2 className="mt-4 font-bold">{form.full_name||"Your name"}</h2><p className="mt-1 text-sm text-black/45">{user.email}</p><span className="mt-3 rounded-full bg-orange-50 px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-orange-700">{user.role}</span></div></Surface><Surface className="p-5 sm:p-7"><h2 className="text-xl font-bold">Personal information</h2><p className="mt-1 text-sm text-black/45">These details are used for your account and checkout.</p><form onSubmit={save} className="mt-6 space-y-5"><div><Label htmlFor="full_name">Full name</Label><div className="relative mt-1.5"><User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-black/30"/><Input id="full_name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} className="h-11 rounded-xl pl-10"/></div></div><div><Label htmlFor="email">Email</Label><div className="relative mt-1.5"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-black/30"/><Input id="email" value={form.email} disabled className="h-11 rounded-xl bg-black/[.03] pl-10"/></div></div><div><Label htmlFor="phone">Phone</Label><div className="relative mt-1.5"><Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-black/30"/><Input id="phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+254..." className="h-11 rounded-xl pl-10"/></div></div><Button disabled={saving} className="h-11 rounded-full bg-orange-500 px-6 font-bold hover:bg-orange-600"><Save className="mr-2 h-4 w-4"/>{saving?"Saving…":"Save changes"}</Button></form></Surface></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><StatCard label="Orders" value={stats.orders} hint="All time" icon={ShoppingBag}/><StatCard label="Active" value={stats.active} hint="In progress" icon={Activity}/><StatCard label="Spent" value={"KSh "+stats.spent.toLocaleString("en-KE",{maximumFractionDigits:0})} hint="Paid orders" icon={WalletCards}/></div></StorePage>;
}