"use client";
import { useEffect,useState } from "react";
import { useUserStore } from "@/lib/stores/userStore";
import { supabase } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
import { Bell, Moon, Sun, Shield, LogOut, Settings as SettingsIcon, KeyRound, ExternalLink } from "lucide-react";
import { useTheme } from "next-themes";
import { PageHero, StorePage, Surface } from "@/components/store-ui";
import Link from "next/link";

export default function SettingsPage(){
 const{user,logout}=useUserStore();const{theme,setTheme}=useTheme();const[loading,setLoading]=useState(true);const[prefs,setPrefs]=useState({email_notifications:true,order_updates:true,marketing_emails:false,sms_notifications:false});
 useEffect(()=>{if(!user)returnvoid supabase.from("profiles").select("preferences").eq("id",user.id).single().then(({data,error})=>{if(error&&error.code!=="PGRST116")throw error;if(data?.preferences)setPrefs(p=>({...p,...data.preferences}))}).catch(()=>toast.error("Could not load preferences")).finally(()=>setLoading(false))},[user]);
 if(!user)return <StorePage><Surface className="mx-auto max-w-lg p-8 text-center"><h1 className="text-2xl font-bold">Sign in to manage settings</h1><Button asChild className="mt-5 rounded-full bg-orange-500 hover:bg-orange-600"><Link href="/auth/login">Sign in</Link></Button></Surface></StorePage>;
 const update=async(key:keyof typeof prefs,value:boolean)=>{const next={...prefs,[key]:value};setPrefs(next);const{error}=await supabase.from("profiles").update({preferences:next,updated_at:new Date().toISOString()}).eq("id",user.id);if(error){setPrefs(prefs);toast.error("Could not save preference")}else toast.success("Preference saved")};
 if(loading)return <StorePage><PageHero eyebrow="SETTINGS" title="Your preferences" description="Loading…"/><div className="h-48 animate-pulse rounded-2xl bg-white"/></StorePage>;
 const rows:[keyof typeof prefs,string,string][]= [["email_notifications","Email notifications","Account and important store updates"],["order_updates","Order updates","Payment, fulfilment and delivery changes"],["marketing_emails","Marketing emails","New products, offers and announcements"],["sms_notifications","SMS notifications","Important updates by text message"]];
 return <StorePage><PageHero eyebrow="SETTINGS" title="Your preferences" description="Control how Ketronics communicates with you and how the store looks."/><div className="grid gap-5 lg:grid-cols-2"><Surface className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-50 text-orange-600"><Bell className="h-5 w-5"/></div><div><h2 className="font-bold">Notifications</h2><p className="text-xs text-black/45">Choose what you want to receive.</p></div></div><div className="mt-6 divide-y divide-black/[.06]">{rows.map(([key,title,desc])=><div key={key} className="flex items-center justify-between gap-5 py-4"><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-black/45">{desc}</p></div><Switch checked={prefs[key]} onCheckedChange={v=>update(key,v)}/></div>)}</div></Surface><Surface className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-50 text-orange-600"><SettingsIcon className="h-5 w-5"/></div><div><h2 className="font-bold">Appearance & security</h2><p className="text-xs text-black/45">Personalize your experience.</p></div></div><div className="mt-6 space-y-3"><div className="flex items-center justify-between rounded-xl bg-[#f6f5f2] p-4"><div className="flex items-center gap-3"><Sun className="h-4 w-4"/><div><p className="text-sm font-semibold">Theme</p><p className="text-xs text-black/45">Choose light, dark or system.</p></div></div><div className="flex gap-1">{["light","dark","system"].map(t=><button key={t} onClick={()=>setTheme(t)} className={`rounded-full px-3 py-1.5 text-[10px] font-bold capitalize ${theme===t?'bg-black text-white':'bg-white text-black/45'}`}>{t==="light"?<Sun className="h-3 w-3"/>:t==="dark"?<Moon className="h-3 w-3"/>:<SettingsIcon className="h-3 w-3"/>}</button>)}</div></div><Link href="/auth/login" className="flex items-center justify-between rounded-xl border border-black/[.07] p-4 hover:border-black/20"><span className="flex items-center gap-3"><KeyRound className="h-4 w-4"/><span><span className="block text-sm font-semibold">Password & account access</span><span className="block text-xs text-black/45">Use the account recovery flow if you need to reset access.</span></span></span><ExternalLink className="h-4 w-4 text-black/30"/></Link><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl border border-red-100 bg-red-50 p-4 text-left text-red-700 hover:bg-red-100"><LogOut className="h-4 w-4"/><span><span className="block text-sm font-semibold">Sign out</span><span className="block text-xs text-red-700/60">End your current session on this device.</span></span></button></div></Surface></div></StorePage>;
}